### ISSUE TITLE
some simple questions about the paper and the code

### ISSUE THREAD

**Issue by LiuYuLOL** [rusty1s/deep-graph-matching-consensus#6]
Hi,

Thanks for the great work. I'm just reading the paper and wondering why the initial loss only uses correct mappings?

Besides, could you explain more about the node function space, e.g., L(G_s) and hat(x_s)?

**Comment by rusty1s** [comment]
Hi and thanks for your interest!

1. Both the initial loss and the refined loss are computed the same way. We make use of negative log-likelihood based on a softmax output (similar to a classification task).
2. Are you referring to Eq. (3) in the paper? We can see the correspondence matrix S as a (soft) map from the nodes in the source graph to the nodes in the target graph. Therefore, we can use it to map node features of one graph to approximate the node features of another graph via x_t = S^T x_s.

I hop this helps!

**Comment by LiuYuLOL** [comment]
Thanks for the prompt reply.  Yes, both answers are greatly helpful. 

1. I mixed it up with negative sampling;
2. Yes, it's about Eq. (3). So the node function`\overrightarrow{x_s}` is the features of node x_s? rather than a way of encoding a node, i.e. (a function)? But what's the difference between `x_s` (of X_s in sec 2) and this `\overrightarrow{x_s}`.
Besides, could you explain it in the code? I'm not sure, but it seems initialized randomly.
>                 r_s = torch.randn((B, N_s, R_in), dtype=h_s.dtype,
>                                   device=h_s.device)

At last, I still have some questions about _sinkhorn_ normalization. 

3. How to implement _sinkhorn_ normalization? (cannot find it in the code, it seems an iterations processing in Cour et al., 2006. 5.2).

4. As far as I understanding _sinkhorn_ aims to fulfill the one-one-mapping constraints, and it (seems) works well in Cour et al., 2006, without refinement. So why say the model is prone to finding false correspondences (sec. 3.2)? Can we regard the refinement is an improvement of _sinkhorn_ normalization?

**Comment by rusty1s** [comment]
2. x_s denotes the features of a node. You can also see it as as a specific instance in the node function space. We approximate this identity by initializing the features randomly.
3. That's correct. We briefly mention in Sec 3.4 that softmax normalization is enough and we do not need the additional power of sinkhorn normalization.
4. I wouldn't call it drawbacks, it's just not defined to resolve ambiguities across neighborhoods. For graph matching, you can well see our refinement approach as an improvement over sinkhorn, because it also takes the assignments of neighbors into account.

**Comment by LiuYuLOL** [comment]
Great! Thanks for your detailed explains.

Still about 2. what's different between the nodes representations of x_s and r_s? Why they are in different spaces?  
Here, follows the code notation. x_s has size=(N_s, dim-256), r_s has size =(B-1, N_s, dim=32). I think the key is to understand ``node indicator functions'' as you mentioned.

**Comment by LiuYuLOL** [comment]
Sorry for the long questions. 

5. I'm not sure my understanding is right for Sec 3.2 Eq 3. Could you correct it?
 Here, node function space L(G) is a collection of functions defined on G (i.e., on all nodes). So for any kind of functions (e.g., arror_x_s) we can have its corresponding functions in the other domain using S. Here, we don't care about the specific form of arror_x_s, we only care about the mapping (and the consensus).

6. So we apply this intuition on Eq 4., substituted with the node indicator function. However, 6.1. how these indicator functions are formed in an identity matrix I_|Vs|? 6.2, then why this matrix could be represented as a dense vector by drawn from N(0,1)?

**Comment by LiuYuLOL** [comment]
A question on neighborhood consensus, what if the two graphs are partially matched? The neighborhood consensus seems a strong requirement that all neighbors should have a matched node. For example, for board nodes, it seems very hard to find all matched neighbors.

**Comment by rusty1s** [comment]
5. we use the terms function and representation interchangeably here (sorry for the confusion). Both terms represent the same thing since a function maps each node to a specific feature representation. Therefore, a node indicator function is a function that uniquely identifies each node, and the identity matrix is a specific instance which fulfills this constraint. 

6. However, identity matrices as inputs to GNNs do not really scale (parameter size is equal to the number of nodes in the graph), and therefore we propose to approximate the identicator function by randomly sampling a low-dimensional node embedding. Since randomly sample new node embeddings for each refinement step, we are still very close to unique identification of nodes (although we have no proofs to justify this claim). Note that we are not interested in applying gradients to the identity (or method should be inductive), we simply use it to match neighborhood colorings across the graphs locally. 

7. You are right that the consensus is a strong requirement, and may need to be adjusted for cases where you only want to partially match the two graphs. However, the formulation in our paper is well be able to find a small subgraph (the source graph) in a larger graph (the target graph).

**Comment by LiuYuLOL** [comment]
What's the identity matrix? Is it a unit matrix?

5. If so, why identity matrix I = dial(1, ..., 1) can represent each node, where |I|= n_s*n_s? 
Besides, why node embedding (i.e., local features in Sec. 3.1) cannot be used in the node indicator functions? (instead, use new specific feature representation)

**Comment by rusty1s** [comment]
5. Yes, its a unit matrix. You can also see it as a one-hot node vector that is different for all nodes in the source graph. Using unique node representations for refinement is the key step of our method. This allows us to aggregate which neighbors belong to which node, and we can test that against the neighborhoods in the target graph. We cannot utilize the given node features here, since they are incapable of doing that. Instead, we use them as input for computing initial assignments.

6. Applying a GNN with node indicators as input results in a high dimensional representation, in which each node holds its own color (its initial representation), and the colors of its neighbors, named o_s. We would except that in perfectly matched graphs, these representations are nearly identical between the matched nodes (except for some noise).

**Comment by LiuYuLOL** [comment]
Great! I got a deeper understanding of the work with your useful comments. Thanks!
